# Generated by Django 4.2.6 on 2023-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=None, max_length=50, verbose_name='Пользователь'),
        ),
    ]
